spring:
  datasource:
    driver-class-name: org.mariadb.jdbc.Driver
    url: ENC(jXaSRmzI27BdK+gbrxrvzQK8uzc2Xs5K0GRfWllXaoe7ubsutqcm3mc+/l8j35+D)
    username: ENC(Febk40BIMGIOcC89rfiHQg==)
    password: ENC(mnVTjMrY+U9HSJZUlMxR8G0OGpksj6Mz)
  sql :
    init :
      #data.sql(더미데이터) 사용부분 미사용시 삭제
      mode : always  
  jpa:
    open-in-view: false
    generate-ddl: true
    show-sql: true
    defer-datasource-initialization : true
    hibernate:
      ddl-auto: create
